# Generated by Django 5.1.4 on 2025-01-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_customuser_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
