# Generated by Django 5.1.4 on 2025-01-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
