# Generated by Django 5.1.4 on 2025-01-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nickname',
        ),
    ]
