# Generated by Django 5.1.4 on 2025-01-15 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_customuser_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
