# Generated by Django 5.1.5 on 2025-01-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_patient_range_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='therapists', through='main.Therapist_Specialization', to='main.specialization'),
        ),
        migrations.AlterModelTable(
            name='therapist_specialization',
            table='main_therapist_specialization',
        ),
    ]
