# Generated by Django 5.1.5 on 2025-02-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_user_languages_user_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='language',
            new_name='languages',
        ),
    ]
