# Generated by Django 5.1.5 on 2025-02-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_language_user_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='languages',
        ),
    ]
