# Generated by Django 5.1.5 on 2025-01-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_therapist_specializations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
    ]
