# Generated by Django 5.1.5 on 2025-01-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_location_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.ManyToManyField(blank=True, through='main.User_Language', to='main.language'),
        ),
    ]
