# Generated by Django 5.1.5 on 2025-02-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_user_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='languages',
            field=models.ManyToManyField(related_name='users', through='main.User_Language', to='main.language'),
        ),
        migrations.AlterModelTable(
            name='user_language',
            table='main_user_language',
        ),
    ]
